import './styles.css';
import Providers from '@/redux/providers';
import NewTemplate from '../../components/template';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default async function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {

    return (
        <div
            style={{
                width: '100%',
                height: '100%',
                padding: '0px',
                margin: '0px',
            }}
        >
            <Providers>
                <NewTemplate>{children}</NewTemplate>
            </Providers>
        </div>
    );
}
