import './styles.css';
import Providers from '@/redux/store/providers';
import Template from '../../common/template';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div className="myBox">
            <Providers>
                <Template children={children}></Template>
            </Providers>
        </div>
    );
}
