import './styles.css';
import Providers from '@/redux/providers';
import NewTemplate from '../../components/template';
import ProtectRoutes from '../../utils/routes/ProtectRoutes';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div className="myBox">
            <Providers>
                <NewTemplate>
                    <ProtectRoutes>{children}</ProtectRoutes>
                </NewTemplate>
            </Providers>
        </div>
    );
}
