import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/redux/providers';
import { Suspense } from 'react';
import Loading from '@/common/loading/Loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <Suspense fallback={<Loading />}>{children}</Suspense>
                </Providers>
            </body>
        </html>
    );
}
