import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/redux/providers';
import { Suspense } from 'react';
import Loading from '@/common/loading/Loading';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import StyledComponentsRegistry from '../common/style/stylesGlobal';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ToastContainer />
                <Providers>
                    <Suspense fallback={<Loading />}>
                        <StyledComponentsRegistry>
                            {children}
                        </StyledComponentsRegistry>
                    </Suspense>
                </Providers>
            </body>
        </html>
    );
}
